name: Deploy docs to AWS

on:
  push:
    branches:
      - PRODUCTION

jobs:
    deploy:
        name: Deploy docs AWS
        runs-on: ubuntu-latest

        steps:
          - name: Repository Dispatch
            uses: peter-evans/repository-dispatch@v2
            with:
              token: ${{ secrets.DISPATCH_GH_TOKEN }}
              repository: Exlint/dashboard
              event-type: docs-production