name: Integration

on:
    pull_request:
        branches: [main]

jobs:
    depcheck:
        name: Testing Depcheck

        runs-on: [self-hosted, Linux, X64, integration]
        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1.2.4
              with:
                  node-version: 18.13.0
                  package-manager: pnpm
                  package-manager-version: 7.26.3

            - name: Test Depcheck
              run: pnpm depcheck:all
