name: Integration

on:
    pull_request:
        branches: [main]

jobs:
    test_depcheck:
        needs: call_pnpm_caching_workflow
        name: Testing Depcheck
        runs-on: ubuntu-latest

        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1.2.1
              with:
                  node-version: 18
                  package-manager: pnpm
                  package-manager-version: 7.26.3

            - name: Test Depcheck
              run: pnpm depcheck

    test_inflint:
        needs: call_pnpm_caching_workflow
        name: Testing Inflint
        runs-on: ubuntu-latest

        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1.2.1
              with:
                  node-version: 18
                  package-manager: pnpm
                  package-manager-version: 7.26.3

            - name: Test Inflint
              run: pnpm inflint
